### ISSUE TITLE
Fixtures take extremely long to load

### ISSUE THREAD

**Issue by PandaWhisperer** [Aethelflaed/mongoid-fixture_set#7]
After managing to get Mongoid::FixtureSet set up with RSpec (see #6), when running my tests, RSpec gets stuck for an extremely long time (30+ seconds) on the loading fixtures step, even though I've only defined a single, very minimal fixture file, `spec/fixtures/currencies.yml`:

``` yaml
usd:
  label: US Dollar
  code: USD
  status: active
  created_by: 2
  updated_by: 2

euro:
  label: Euro
  code: EUR
  status: active
  created_by: 2
  updated_by: 2
```

After the long wait, it eventually fails with the following error:

```
TypeError:
    no implicit conversion of nil into String
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set.rb:69:in `join'
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set.rb:69:in `block in create_fixtures'
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set.rb:64:in `map'
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set.rb:64:in `create_fixtures'
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set/test_helper.rb:91:in `load_fixtures'
# ~/.rvm/gems/ruby-2.2.4/gems/mongoid-fixture_set-1.5.0/lib/mongoid/fixture_set/test_helper.rb:75:in `setup_fixtures'
# ./spec/routes/categories_spec.rb:41:in `block (2 levels) in <top (required)>'

```
